#!/usr/bin/env escript

-include_lib("kernel/include/file.hrl").

print_usage() ->
  io:format("./emd5sum <file name>~n").

main([Filename]) ->
  {ok, Data} = file:read_file(Filename),
  Sum = erlang:md5(Data),
  io:format("~s~n", [hex_string(Sum)]),
  halt(0);
main(_) ->
  % Print usage message if invalid number of arguments is passed in
  print_usage(),
  halt(1).

% From https://stackoverflow.com/questions/3768197/erlang-ioformatting-a-binary-to-hex
% We need to format each byte in the hex binary as a set of two ascii
% characters in order to construct an printable string of characters.
hex_string(HexBin) ->
    [io_lib:format("~2.16.0B",[X]) || <<X:8>> <= HexBin].
